---

- name: Log into registry.camunda.cloud
  docker_login:
    registry: registry.camunda.cloud
    username: "{{ camunda_enterprise_user }}"
    password: "{{ camunda_enterprise_password }}"
    reauthorize: yes

- name: Download and run Camunda Enterprise Container
  docker_container:
    name: camunda
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:7.10.0
    state: started
    ports:
     - "{{ camunda_port }}:8080"

...
